services:
  eipscanner-dev:
    container_name: eipscanner_devcontainer
    build:
      context: ../
      dockerfile: Dockerfile
      # Do not build the library for the devcontainer
      target: build_devcontainer
    entrypoint: /bin/bash -c "sleep inf"
    volumes:
      - ..:/workspaces/eipscanner/
    network_mode: "host"